[package]
name = "battery_rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "led_panel"
path = "src/led_panel.rs"

[[bin]]
name = "battery"
path = "src/battery.rs"

[dependencies]
rosrust = "0.9"
rosrust_msg = "0.1"
env_logger = "0.10"
log = "0.4.27"